### ISSUE TITLE
The reference is invalid

### ISSUE THREAD

**Issue by JiaxiangBU** [hoehleatsu/hoehleatsu.github.io#2]
https://github.com/hoehleatsu/hoehleatsu.github.io/blob/2869a7654b553b1ad967ccdd6690653a82612e1b/_source/2020-03-16-flatteningthecurve.Rmd#L58

See the screenshot of this post.

![image](https://user-images.githubusercontent.com/15884785/76723875-cb746100-6783-11ea-869c-79a3158e2375.png)

**Comment by mhoehle** [comment]
Thanks for the interest in the post and the GitHub issue. The link here goes to Twitter, so maybe twitter could not be reached or there was a problem fetching the page? 

In the original post the result of the linking looks good and also on R-Bloggers:
https://staff.math.su.se/hoehle/blog/2020/03/16/flatteningthecurve.html

![grafik](https://user-images.githubusercontent.com/5960279/76907208-f3f47c00-68a5-11ea-8b8f-64ae424548ed.png)

Thus not sure, I know how to fix the problem. Could you confirm, that the problem still exists and describe in more detail, how to reproduce it?

**Comment by JiaxiangBU** [comment]
@hoehleatsu Yes, it still does not work. I think because I cannot log in twitter because the Internet is Forbidden or Limited.
I will close it because the Rmd document is compiled well

**Comment by mhoehle** [comment]
Cool, thanks for posting the issue anyway!
